# Generated by Django 5.0.6 on 2024-08-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_category_name_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='/no_image.png', upload_to='images/items'),
        ),
    ]
