# Generated by Django 5.0.6 on 2024-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_menu_image_alter_menu_item_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
